version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thunderbot-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - backend_thunderbot-network

networks:
  backend_thunderbot-network:
    external: true